In [1]:
# Imports
import torch
import numpy as np

In [2]:
# Tensor
x = torch.Tensor(5, 3)
print x


 1.4394e-37  0.0000e+00 -2.2626e+00
 4.5829e-41 -2.2999e+00  4.5829e-41
 3.0697e-38  0.0000e+00  3.0697e-38
 0.0000e+00 -1.9955e+05  4.5829e-41
-2.3427e+00  4.5829e-41 -2.3426e+00
[torch.FloatTensor of size 5x3]



In [5]:
# Construct a randomly initialized matrix
y = torch.rand(5, 3)
print y


 0.1421  0.7358  0.1672
 0.8472  0.4381  0.2019
 0.2403  0.1050  0.1855
 0.2767  0.8235  0.6025
 0.3804  0.0654  0.1156
[torch.FloatTensor of size 5x3]



In [6]:
# Get size of a tensor
print x.size()

torch.Size([5, 3])


In [7]:
# Addition: 1
z = x + y
print z


 0.9214  1.0472  0.3798
 1.5228  0.7140  0.8238
 0.7340  0.7747  0.6769
 0.5868  1.7342  1.5584
 1.0959  0.8855  0.8179
[torch.FloatTensor of size 5x3]



In [8]:
# Addition: 2
z = torch.add(x, y)
print z


 0.9214  1.0472  0.3798
 1.5228  0.7140  0.8238
 0.7340  0.7747  0.6769
 0.5868  1.7342  1.5584
 1.0959  0.8855  0.8179
[torch.FloatTensor of size 5x3]



In [9]:
# Addition: Giving an output tensor
result = torch.Tensor(x.size())
torch.add(x, y, out=result)
print result


 0.9214  1.0472  0.3798
 1.5228  0.7140  0.8238
 0.7340  0.7747  0.6769
 0.5868  1.7342  1.5584
 1.0959  0.8855  0.8179
[torch.FloatTensor of size 5x3]



In [10]:
# Addition: In-Place
# NOTE: Any operation that mutates a tensor in-place is post fixed with an "_"
print y[2, 2]
y.add_(x)
print y[2, 2]

0.185483187437
0.676866710186


In [11]:
# Indexing
print x[:, 1]


 0.3114
 0.2759
 0.6697
 0.9107
 0.8202
[torch.FloatTensor of size 5]



**[PyTorch Documentation](http://pytorch.org/docs/torch)**

### Converting Torch Tensor to a NumPy Array and vice versa

In [22]:
# Torch Tensor to Numpy Array
a = torch.ones(5)
print a, type(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]
 <class 'torch.FloatTensor'>


In [23]:
b = a.numpy()
print b, type(b)

[ 1.  1.  1.  1.  1.] <type 'numpy.ndarray'>


In [24]:
a.add_(1)
print a
print b


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [25]:
# NumPy Array to Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print a
print b

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



### CUDA Tensors

In [27]:
# If CUDA is available run this cell
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print x + y


 1.7006  1.3586  0.5925
 2.1983  0.9899  1.4457
 1.2277  1.4444  1.1683
 0.8970  2.6448  2.5143
 1.8113  1.7057  1.5203
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

