In [1]:
# Imports
import time
import mxnet as mx
import numpy as np

**NDArray** - Multidimensional fixed size array

In [2]:
# Create a 1-dimensional array with a list
a = mx.nd.array([1, 2, 3])
print 'Shape: ', a.shape
print 'Type: ', a.dtype
print 'Size: ', a.size
print 'Context: ', a.context

Shape:  (3L,)
Type:  <type 'numpy.float32'>
Size:  3
Context:  cpu(0)


In [3]:
# Create a 2-dimensional array with a nested list
b = mx.nd.array([[1, 2, 3], [4, 5, 6]])
print 'Shape: ', b.shape
print 'Type: ', b.dtype
print 'Size: ', b.size
print 'Context: ', b.context

Shape:  (2L, 3L)
Type:  <type 'numpy.float32'>
Size:  6
Context:  cpu(0)


In [4]:
# Create an array from NumPy ndarray object
c = np.arange(15).reshape(3, 5)
a = mx.nd.array(c)
print 'Shape: ', a.shape
print 'Type: ', a.dtype
print 'Size: ', a.size
print 'Context: ', a.context

Shape:  (3L, 5L)
Type:  <type 'numpy.float32'>
Size:  15
Context:  cpu(0)


In [5]:
# Create an array (float32 default)
a = mx.nd.array([1, 2, 3])
print 'Type: ', a.dtype

# Create an int32 array
b = mx.nd.array([1, 2, 3], dtype=np.int32)
print 'Type: ', b.dtype

# Create a 16 bit float array
c = mx.nd.array([1, 2, 3], dtype=np.float16)
print 'Type: ', c.dtype

Type:  <type 'numpy.float32'>
Type:  <type 'numpy.int32'>
Type:  <type 'numpy.float16'>


In [6]:
# Create a same shape array with all elements set to 5
c = mx.nd.full(shape=(3, 5),val=5)
print c


[[ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]]
<NDArray 3x5 @cpu(0)>


In [7]:
# Create a same shape array whose initial content is random
d = mx.nd.empty(shape=(3, 3))
print d


[[  0.00000000e+00   0.00000000e+00   2.60447261e-37]
 [  0.00000000e+00  -1.33974318e-25   4.56472975e-41]
 [  1.93086432e-13   4.56472975e-41   6.72623263e-44]]
<NDArray 3x3 @cpu(0)>


In [8]:
# Printing array
b = mx.nd.arange(18).reshape((3, 2, 3))
b.asnumpy()

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.]],

       [[  6.,   7.,   8.],
        [  9.,  10.,  11.]],

       [[ 12.,  13.,  14.],
        [ 15.,  16.,  17.]]], dtype=float32)

In [9]:
# Basic Operations
a = mx.nd.ones((2, 3))
b = mx.nd.ones((2, 3))

# Elementwise sum
c = a + b
print c

# Elementwise difference
d = a - b
print d

# Elementwise power and sine, then transpose
e = mx.nd.sin(c**2).T
print e

# Elementwise max
f = mx.nd.maximum(c, a)
print f

# Elementwise multiplication
g = mx.nd.arange(12).reshape((4, 3))
h = g * g
print h


[[ 2.  2.  2.]
 [ 2.  2.  2.]]
<NDArray 2x3 @cpu(0)>

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
<NDArray 2x3 @cpu(0)>

[[-0.7568025 -0.7568025]
 [-0.7568025 -0.7568025]
 [-0.7568025 -0.7568025]]
<NDArray 3x2 @cpu(0)>

[[ 2.  2.  2.]
 [ 2.  2.  2.]]
<NDArray 2x3 @cpu(0)>

[[   0.    1.    4.]
 [   9.   16.   25.]
 [  36.   49.   64.]
 [  81.  100.  121.]]
<NDArray 4x3 @cpu(0)>


In [10]:
# Dot Product
a = mx.nd.arange(12).reshape((4, 3))
b = mx.nd.dot(a, a.T)
print b


[[   5.   14.   23.   32.]
 [  14.   50.   86.  122.]
 [  23.   86.  149.  212.]
 [  32.  122.  212.  302.]]
<NDArray 4x4 @cpu(0)>


In [11]:
# += operator
a = mx.nd.ones((2,2))
b = mx.nd.ones(a.shape)
b += a
b.asnumpy()

array([[ 2.,  2.],
       [ 2.,  2.]], dtype=float32)

In [12]:
# Indexing and Slicing
a = mx.nd.arange(6).reshape((3, 2))
print a
print a[1:2]
a[1:2] = 1
print a
a[:].asnumpy()


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]]
<NDArray 3x2 @cpu(0)>

[[ 2.  3.]]
<NDArray 1x2 @cpu(0)>

[[ 0.  1.]
 [ 1.  1.]
 [ 4.  5.]]
<NDArray 3x2 @cpu(0)>


array([[ 0.,  1.],
       [ 1.,  1.],
       [ 4.,  5.]], dtype=float32)

In [13]:
# Slice a particular axis
d = mx.nd.slice_axis(a, axis=1, begin=1, end=2)
d.asnumpy()

array([[ 1.],
       [ 1.],
       [ 5.]], dtype=float32)

In [14]:
# Shape Manipulation
a = mx.nd.array(np.arange(24))
b = a.reshape((2, 3, 4))
print b.shape
b.asnumpy()

(2L, 3L, 4L)


array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]],

       [[ 12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.],
        [ 20.,  21.,  22.,  23.]]], dtype=float32)

In [15]:
# Concat: Stack multiple arrays along the first axis
a = mx.nd.ones((2, 3))
b = mx.nd.ones((2, 3)) * 2
c = mx.nd.concat(a, b)
c.asnumpy()

array([[ 1.,  1.,  1.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  2.,  2.,  2.]], dtype=float32)

In [16]:
# Reduce: sum
a = mx.nd.ones((2, 3))
b = mx.nd.sum(a)
b.asnumpy()

array([ 6.], dtype=float32)

In [17]:
# Reduce: sum (along an axis)
c = mx.nd.sum_axis(a, axis=1)
c.asnumpy()

array([ 3.,  3.], dtype=float32)

In [18]:
# Broadcast
a = mx.nd.array(np.arange(6).reshape(6, 1))
b = a.broadcast_to((6, 4))
b.asnumpy()

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.]], dtype=float32)

In [19]:
# Copies
a = mx.nd.ones((2, 2))
b = a
print b is a
b = a.copy() # allocate a new NDArray and assigns to b
print b is a

True
False


In [ ]:
# GPU
gpu_device = mx.gpu(device_id=0)

def f():
    a = mx.nd.ones((100, 100))
    b = mx.nd.ones((100, 100))
    c = a + b
    print c

f() # Default: mx.cpu() is used

# Change default context to the first GPU
with mx.Context(gpu_device):
    f()

In [ ]:
# Specify the context when creating an array
a = mx.nd.ones((100, 100), gpu_device)
a

In [ ]:
# MXNet requires 2 arrays to be on the same device for computation. Copy data between devices
a = mx.nd.ones((100, 100), mx.cpu())
b = mx.nd.ones((100, 100), gpu_device)
c = mx.nd.ones((100, 100), gpu_device)
# a + b # Error

a.copyto(c) # Copy from CPU to GPU
d = b + c
e = b.as_in_context(c.context) + c
{'d': d, 'e': e}

In [20]:
# Serialize From/To Filesystems: save or load data to/from disk
import pickle as pkl

a = mx.nd.ones((2, 3))

# Pack and then dump into disk
data = pkl.dumps(a)
pkl.dump(data, open('temp.pickle', 'wb'))

# Load from disk and then unpack
data = pkl.load(open('temp.pickle', 'rb'))
b = pkl.loads(data)
b.asnumpy()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [21]:
# Save or Load using MXNet
a = mx.nd.ones((2,3))
b = mx.nd.ones((5,6))

mx.nd.save('temp.ndarray', [a, b])
c = mx.nd.load('temp.ndarray')
c

[
 [[ 1.  1.  1.]
  [ 1.  1.  1.]]
 <NDArray 2x3 @cpu(0)>, 
 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]
 <NDArray 5x6 @cpu(0)>]

In [22]:
# Save or Load a dict of NDArrays
d = {'a': a, 'b': b}
mx.nd.save('temp.ndarray', d)
c = mx.nd.load('temp.ndarray')
c

{'a': 
 [[ 1.  1.  1.]
  [ 1.  1.  1.]]
 <NDArray 2x3 @cpu(0)>, 'b': 
 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]
 <NDArray 5x6 @cpu(0)>}

In [23]:
# Lazy Evaluation
def do(x, n):
    """
    Push computation into the backend engine
    """
    return [mx.nd.dot(x, x) for _ in range(n)]

def wait(x):
    """
    Wait until all results are available
    """
    for y in x:
        y.wait_to_read()
        
tic = time.time()
a = mx.nd.ones((1000, 1000))
b = do(a, 50)
print 'Time for all computations are pushed into the backend engine: \n %f sec' % (time.time() - tic)
wait(b)
print 'Time for all computations are finished: \n %f sec' % (time.time() - tic)

Time for all computations are pushed into the backend engine: 
 0.002782 sec
Time for all computations are finished: 
 4.352992 sec


In [26]:
n = 10
a = mx.nd.ones((1000, 1000))
#b = mx.nd.ones((6000, 6000), gpu_device)
tic = time.time()
c = do(a, n)
wait(c)
#print 'Time to finish the CPU workload: %f sec' % (time.time() - tic)
#d = do(b, n)
#wait(d)
print 'Time to finish both CPU/gPU workloads: %f sec' % (time.time() - tic)

Time to finish both CPU/gPU workloads: 0.996069 sec


In [27]:
tic = time.time()
c = do(a, n)
#d = do(b, n)
wait(c)
#wait(d)
print('Both finished in: %f sec' % (time.time() - tic))

Both finished in: 1.016243 sec
