In [1]:
# Imports

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # Avoid TF warning messages

import tensorflow as tf

In [2]:
# Simple Graph
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

with tf.Session() as sess:
    print sess.run(x)

5


**Visualize with TensorBoard**
- Create the summary writer after graph definition and before running session

```bash
source ~/TensorFlow/bin/activate
cd TensorFlow/notebooks/
tensorboard --logdir="./graphs" --port 6006
```

Then open browser and go to: `http://localhost:6006/`

In [3]:
# Visualize Simple Graph with TensorBoard: Summary Filewriter inside session
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

with tf.Session() as sess:
    
    # Create 'summary' writer after graph definition and before running session
    writer = tf.summary.FileWriter('./graphs', sess.graph) # 
    
    # Run session
    print sess.run(x)

# Close writer
writer.close()
print a, b, x

5
Tensor("Const_2:0", shape=(), dtype=int32) Tensor("Const_3:0", shape=(), dtype=int32) Tensor("Add_1:0", shape=(), dtype=int32)


In [4]:
# Visualize Simple Graph with TensorBoard: Summary Filewriter outside session
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    
    # Run session
    print sess.run(x)

# Close writer
writer.close()
print a, b, x

5
Tensor("Const_4:0", shape=(), dtype=int32) Tensor("Const_5:0", shape=(), dtype=int32) Tensor("Add_2:0", shape=(), dtype=int32)


**Explicitly Naming Nodes**

In [5]:
# Naming nodes
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

with tf.Session() as sess:
    
    # Create 'summary' writer after graph definition and before running session
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    
    # Run session
    print sess.run(x)

# Close writer
writer.close()
print a, b, x

5
Tensor("a:0", shape=(), dtype=int32) Tensor("b:0", shape=(), dtype=int32) Tensor("add:0", shape=(), dtype=int32)


#### Constant
- A constant's value is stored in the graph
```python
tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
```

In [6]:
# Constant

# Constant of 1D tensor (vector)
a = tf.constant([2, 2], name='a')

# Constant of 2x2 tensor (matrix)
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.add(a, b, name='add')
y = tf.multiply(a, b, name='mul')

with tf.Session() as sess:
    x, y = sess.run(fetches=[x, y])
    print x
    print y

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]


#### Tensors filled with a specific value

```python
# Create a tensor of shape and all elements are zeros
tf.zeros(shape, dtype=tf.int32, name=None)

# Create a tensor of shape and type as the input_tensor but all elements are zeros
tf.zeros_like(input_tensor, dtype=tf.float32, name=None, optimize=True)

# Create a tensor of shape and all elements are ones
tf.ones(shape, dtype=tf.int32, name=None)

# Create a tensor of shape and type as the input_tensor but all elements are ones
tf.ones_like(input_tensor, dtype=tf.float32, name=None, optimize=True)

# create a tensor filled with a scalar value
tf.fill(dims, value, name=None)
```

In [7]:
# Zeros
z = tf.zeros([2, 3], dtype=tf.float32)

# Zeros like
input_tensor = [[0, 1], [2, 3], [4, 5]]
zl = tf.zeros_like(input_tensor)

# Ones
o = tf.ones([2, 3], dtype=tf.int32)

# Ones like
ol = tf.ones_like(input_tensor)

# Fill
f = tf.fill([3, 3], 3.14)

with tf.Session() as sess:
    z, zl, o, ol, f = sess.run(fetches=[z, zl, o, ol, f])
    print z
    print zl
    print o
    print ol
    print f
    print 
    

# Zeros like and ones like using string and bool
s = ['apple', 'banana', 'mango']
sz = tf.zeros_like(s)
# so = tf.ones_like(s) # TypeError: Expected string, got 1 of type 'int' instead.

with tf.Session() as sess:
    sz = sess.run(fetches=[sz])
    print sz
    print
    

b = [[True, False],
     [True, True]]

bz = tf.zeros_like(b) # All elements are False
bo = tf.ones_like(b) # All elements are True

with tf.Session() as sess:
    bz, bo = sess.run(fetches=[bz, bo])
    print bz
    print bo

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]]
[[1 1]
 [1 1]
 [1 1]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]

[array(['', '', ''], dtype=object)]

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


#### Constants as sequences

```python
# Return evenly spaced numbers over a specified interval
tf.linspace(start, stop, num, name=None)

# Range
tf.range(start, limit=None, delta=1, dtype=None, name='range')

# NOTE: Unlike NumPy or Python sequences, Tensor objects are not iterable (TypeError)
```

In [8]:
# Linspace
ls = tf.linspace(start=1.0, stop=15.0, num=3)

# Range
r = tf.range(start=3, limit=18, delta=3)
rl = tf.range(9, delta=2)

with tf.Session() as sess:
    ls, r, rl = sess.run(fetches=[ls, r, rl])
    print ls
    print r
    print rl

[ 1.  8. 15.]
[ 3  6  9 12 15]
[0 2 4 6 8]


#### Randomly Generated Constants

```python
# Random Normal
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

# Random Truncated Normal: values with magnitude > 2 standard deviations from the mean are dropped and re-picked
tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

# Random Uniform
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

# Random Shuffle: Randomly shuffles a tensor along its first dimension
tf.random_shuffle(value, seed=None, name=None)

# Random Crop: Randomly crops a tensor to a given size
tf.random_crop(value, size, seed=None, name=None)

# Multinomial: Draws samples from a multinomial distribution
tf.multinomial(logits, num_samples, seed=None, name=None)

# Draws shape samples from each of the given Gamma distribution(s)
tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None) 

# Set Random Seed
tf.set_random_seed(seed)
```

In [9]:
# Random Normal
rn = tf.random_normal(shape=[1, 3], mean=0.0, stddev=3.0, dtype=tf.float32)

# Truncated Normal
tn = tf.truncated_normal(shape=[1, 3], mean=0.0, stddev=3.0, dtype=tf.float32)

# Random Uniform
ru = tf.random_uniform(shape=[1, 3], maxval=10.0, dtype=tf.float16)

# Random Shuffle
x = tf.constant([[0, 1], [2, 3], [4, 5]], name='x')
rs = tf.random_shuffle(value=x, seed=5)

# Random Crop
rc = tf.random_crop(value=x, size=[1, 2], seed=3)

# Multinomial
m = tf.multinomial(logits=tf.log([[10., 10.]]), num_samples=5)

# Random Gamma
rg = tf.random_gamma(shape=[1, 3], alpha=[0.5, 1.5])

with tf.Session() as sess:
    rn, tn, ru, x, rs, rc, m, rg = sess.run(fetches=[rn, tn, ru, x, rs, rc, m, rg])
    print rn
    print tn
    print ru
    print x, '\n', rs
    print rc
    print m
    print rg

[[-5.7712817  -1.6136539   0.26798758]]
[[-3.1015658 -0.260984   2.8279536]]
[[8.9   9.305 5.88 ]]
[[0 1]
 [2 3]
 [4 5]] 
[[2 3]
 [4 5]
 [0 1]]
[[2 3]]
[[1 0 1 0 1]]
[[[0.01468982 0.6943322 ]
  [0.40348473 1.0148591 ]
  [0.9756383  1.1467177 ]]]


**Math Operations**

In [10]:
# Constants
a = tf.constant([3, 6])
b = tf.constant([2, 2])

# Add
add = tf.add(a, b)

# Add: Equivalent to a + b + b
add_n = tf.add_n([a, b, b])

# Multiply
mul = tf.multiply(a, b)

# Matrix Multiply
# matmul = tf.matmul(a, b) # ValueError
matmul = tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1]))

# Division
div = tf.div(a, b)

# Mod
mod = tf.mod(a, b)

with tf.Session() as sess:
    add, add_n, mul, matmul, div, mod = sess.run(fetches=[add, add_n, mul, matmul, div, mod])
    print add
    print add_n
    print mul
    print matmul
    print div
    print mod

[5 8]
[ 7 10]
[ 6 12]
[[18]]
[1 3]
[1 0]


In [11]:
# Div
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')

with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))
    print(sess.run(tf.divide(b, a)))
    print(sess.run(tf.truediv(b, a)))
    print(sess.run(tf.floordiv(b, a)))
    # print(sess.run(tf.realdiv(b, a))) # Error: Only works for real values
    print(sess.run(tf.truncatediv(b, a)))
    print(sess.run(tf.floor_div(b, a)))

[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


`tf.matmul` no longer does dot product. It multiplies matrices of ranks greater or equal to 2. Use `tf.tensordot` to do dot product

In [12]:
# Dot Product
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')

with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b)))
    # print(sess.run(tf.matmul(a, b))) # ValueError
    print(sess.run(tf.tensordot(a, b, axes=1)))

[20 60]
80


- **Do not use Python native types for tensors because TensorFlow has to infer Python type**
- Constants are stored in the graph definition - **this makes loading graphs expensive when constants are big**
- Only use constants for primitive types. Use `variables` or readers for more data that requires more memory
- NOTE: `tf.Session.run()` output will be a NumPy array

In [13]:
# Treated as 0-D tensor (scalar)
t_0 = 19
a = tf.ones_like(t_0)

# Treated as 1-D tensor (vector)
t_1 = [b'apple', b'peach', b'grape']
b = tf.zeros_like(t_1) # tf.ones_like returns TypeError

# Treated as 2-D tensor (matrix)
t_2 = [[True, False],
       [False, True]]
c = tf.ones_like(t_2)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

1
['' '' '']
[[ True  True]
 [ True  True]]


NOTE: you will see value of `constant` stored in the graph’s definition - This makes loading graphs expensive when constants are big

In [14]:
# Print graph definition to check s are stored in graph definition
constant = tf.constant([1.5, 3.14], name="constant")

with tf.Session() as sess:
    print 
#     print sess.graph.as_graph_def()

# NOTE: you will see value of `constant` stored in the graph’s definition - This makes loading
# graphs expensive when constants are big

**Variables**
- `tf.constant` is an operation
- `tf.Variable` is a class with multiple operations
```python
x = tf.Variable(...)
x.initializer # Initialize
x.value() # Read operation
x.assign() # Write operation
# and more
```

- `tf.Variable` holds several operations, e.g. `x = tf.Variable(...)`
    - `x.initializer` - Initializer operation for variable x
    - `x.read()` - Returns last snapshot of variable x
    - `x.assign(...)` - Assigns a new value to variable x
    - `x.assign_add(...)` - Adds a value to variable x


- **Old way to create a variable: `tf.Variable(<initial-value>, name=<optional-name>)`. However the old way is discouraged and use of `tf.get_variable(...)` is encouraged because it allows for easy variable sharing**
- **`Need to initialize variables`** before using them

In [15]:
## OLD

# Variable with a scalar value
a = tf.Variable(2.0, name='scalar')

# Variable as a vector
b = tf.Variable([1, 2, 3], name='vector')

# Variable as a matrix
c = tf.Variable([[1, 2, 3], [4, 5, 6]], name='matrix')

# Variable as tensor filled with zeros (with dtype = int32)
d = tf.Variable(tf.zeros(shape=[2, 3], dtype=tf.int32), dtype=tf.int32)

# Initialize all variables at once
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    a, b, c, d = sess.run(fetches=[a, b, c, d])
    print a
    print b
    print c
    print d

2.0
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [16]:
# Initialize sub-set of variables

# Variable with a scalar value
a = tf.Variable(2.0, name='scalar')

# Variable as a vector
b = tf.Variable([1, 2, 3], name='vector')

# Variable as a matrix
c = tf.Variable([[1, 2, 3], [4, 5, 6]], name='matrix')

init_ab = tf.variables_initializer([a, b], name='init_ab')

with tf.Session() as sess:
    sess.run(init_ab)
    x, y = sess.run(fetches=[a, b])
    print x
    print y

2.0
[1 2 3]


In [17]:
# Initialize a single variable
W = tf.Variable([[1, 2, 3], [4, 5, 6]], name='w')

with tf.Session() as sess:
    sess.run(W.initializer)
    w = sess.run(fetches=[W])
    print w

[array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)]


In [18]:
# eval() a variable
W = tf.Variable(tf.truncated_normal([3, 4]))

with tf.Session() as sess:
    sess.run(W.initializer)
    print 'Without eval(): \n', W
    print
    print 'With eval(): \n', W.eval()

Without eval(): 
<tf.Variable 'Variable_1:0' shape=(3, 4) dtype=float32_ref>

With eval(): 
[[-0.82705754 -0.8364552  -0.23719323 -0.24641643]
 [ 0.742202    0.81145614 -0.8818793  -0.5014315 ]
 [ 0.21253167 -1.8766396  -0.09812596  0.31320867]]


In [19]:
# tf.Variable.assign()
W = tf.Variable(10)

W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval() # Returns: 10 but we assigned 100!

10


# New Way: `tf.get_variable(...)`

In [20]:
# NEW
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable('big_matrix', shape=(3, 4), initializer=tf.zeros_initializer())

In [21]:
# Get a list of uninitialized variables
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))

['scalar' 'vector' 'matrix' 'Variable' 'scalar_1' 'vector_1' 'matrix_1'
 'w' 'Variable_1' 'Variable_2' 'scalar_2' 'matrix_2' 'big_matrix']


In [22]:
# Initialize only a subset of variables
with tf.Session() as sess:
    sess.run(tf.variables_initializer([s, m]))
    print(sess.run(s))
    print(sess.run(m))

2
[[0 1]
 [2 3]]


In [23]:
# Initialize all variables at once
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(s))
    print(sess.run(m))
    print(sess.run(W))

2
[[0 1]
 [2 3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# Initialize variable separately
with tf.Session() as sess:
    sess.run(W.initializer)
    print(sess.run(W))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# Get variable's value
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(W.eval())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
# W.assign(100) does not assign the value 100 to W. It creates an assign op, 
# and that op needs to be run to take effect.

W = tf.Variable(10)

assign_op = W.assign(100)
with tf.Session() as sess:
    # sess.run(W.initializer) # No need to initialize variable because assign_op does it
    sess.run(assign_op)
    print W.eval() # Returns: 100

100


In [27]:
# tf.Variable.assign()

tf.reset_default_graph()

a = tf.get_variable('a', initializer=tf.constant(2))
a_x_2 = a.assign(2 * a) # assign a * 2 to a and call this operation a_x_2

with tf.Session() as sess:
    sess.run(a.initializer)
    print sess.run(a_x_2)

4


In [28]:
# tf.Variable.assign()

tf.reset_default_graph()

a = tf.get_variable('a', initializer=tf.constant(2))
a_x_2 = a.assign(2 * a)

with tf.Session() as sess:
    sess.run(a.initializer)
    print sess.run(a_x_2)
    print sess.run(a_x_2) # a * 2 is assigned to a every time a_x_2 is fetched

4
8


In [29]:
# tf.Variable.assign()

tf.reset_default_graph()

a = tf.get_variable('a', initializer=tf.constant(2))
a_x_2 = a.assign(2 * a)

with tf.Session() as sess:
    sess.run(a.initializer)
    print sess.run(a_x_2)
    print sess.run(a_x_2)
    print sess.run(a_x_2)

4
8
16


In [30]:
# tf.Variable.assign_add() and tf.Variable.assign_sub()

a = tf.Variable(10)

with tf.Session() as sess:
    # Initialize variable a
    sess.run(a.initializer)
    
    # Increment by 10
    sess.run(a.assign_add(10))
    print a.eval()
    
    # Decrement by 10
    sess.run(a.assign_sub(4))
    print a.eval()
    
# NOTE: assign_add() and assign_sub() cant initialize variable a because
# these operations need the original value of a

20
16


In [31]:
# Each session maintains its own copy of variable
W = tf.Variable(10)

with tf.Session() as sess1:
    sess1.run(W.initializer)
    sess1.run(W.assign_add(10))
    print 'Session-1 W: ', W.eval()
    
with tf.Session() as sess2:
    sess2.run(W.initializer)
    sess2.run(W.assign_sub(2))
    print 'Session-2 W: ', W.eval()

Session-1 W:  20
Session-2 W:  8


In [32]:
# Use a variable to initialize another variable

W = tf.Variable(tf.truncated_normal([3, 4]))
U = tf.Variable(2 * W)

with tf.Session() as sess:
    sess.run(U.initializer)
    print U.eval()
    
# NOTE: This is not so safe

[[ 0.95741385 -3.835653    2.8480554  -0.48037145]
 [-0.27191997 -0.8774682   1.1555811   1.0937985 ]
 [ 1.3925575   0.36849758 -1.1364259   1.3934553 ]]


In [33]:
# Use a variable to initialize another variable (Safer)

W = tf.Variable(tf.truncated_normal([3, 4]))
U = tf.Variable(2 * W.initialized_value())

with tf.Session() as sess:
    sess.run(U.initializer)
    print U.eval()

[[-2.1318662  -0.14832701  2.1263435   3.1958468 ]
 [-1.2384382   0.8329352  -0.30067134 -0.5858361 ]
 [ 0.8151971   0.81219125  0.73745626  1.3220427 ]]


**Interactive Session** - It makes itself default session so `run()` or `eval()` can be called without explicitly calling the session. Convenient in IPython notebooks. However, it is complicated when there are multiple sessions to run

In [34]:
# Session vs InteractiveSession
sess = tf.InteractiveSession()

a = tf.constant(5.0)
b = tf.constant(3.0)
c = a * b
print c.eval()

sess.close()

15.0


**Control Dependencies** - Defines which `operations` should be run first using `tf.Graph.control_dependencies(control_inputs)`

If graph `g` has 5 operations: a, b, c, d, e
```python
with g.control_dependencies([a, b, c]):
    # `d` and `e` will only run after `a`, `b`, and `c` have executed.
    d = ...
    e = ...
```

### Old Way 
**Placeholder** + `feed_dict` (Easy to use but poor performance)

A TensorFlow program often has 2 phases:

1. Assemble a graph
2. Use a session to execute operations in the graph

NOTE: Graph can be assembled first without knowing the values needed for computation. Analogy: $f(x, y) = x^2 + y$ can be defined without knowing the value of $x$ or $y$. 

`x , y` are placeholders for the actual values. The values can later be supplied when computation needs to be executed.

`tf.placeholder(dtype, shape=None, name=None)` where `shape=None` means that tensor of any shape will be accepted as value for placeholder. NOTE: `shape=None` is easy to use but nightmarish for debugging, and using it also breaks all following shape inference, which makes many operations not work because they expect certain rank.

In [56]:
# Create a placeholder of type float 32 bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])

# Create a constant of type float 32 bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], dtype=tf.float32)

c = tf.add(a, b)

with tf.Session() as sess:
#     print sess.run(c) # Error because placeholder does not have any value
    print

In [57]:
# Feed the values to a placeholder using a dictionary
with tf.Session() as sess:
    # Feed [1, 2, 3] to placeholder via dict {a: [1, 2, 3]}
    print sess.run(c, feed_dict={a: [1, 2, 3]})

[ 6.  7.  8.]


In [58]:
# Feeding multiple data points 

list_a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

with tf.Session() as sess:
    for a_value in list_a:
        print sess.run(c, feed_dict={a: a_value})

[ 6.  7.  8.]
[  9.  10.  11.]
[ 12.  13.  14.]


In [59]:
# Feeding values to TF operations

# Creaete operations, tensors, etc
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    replace_dict = {a: 15} # To replace value of a
    print sess.run(b, feed_dict=replace_dict)

45


**Check if a tensor is feedable or feetchable**

`tf.Graph.is_feedable(tensor)` or `tf.Graph.is_fetchable(tensor)`

### Lazy Loading (avoid as it is disadvantageous)
- Defer creating/initializing an object until it is needed
- To avoid this separate the definition of operations and their execution when possible. When it is not possible group related operations into classes and use Python property to ensure function is only loaded once when it is first called.
- [Defining the computation graph](https://danijar.com/structuring-your-tensorflow-models/)

In [60]:
import tensorflow as tf

# Normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # Create the "add" node before executing the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./normal_loading', sess.graph)
    for _ in range(10):
        sess.run(z)
    writer.close()

In [61]:
# Check graph definition
# tf.get_default_graph().as_graph_def()

**Normal** loading - Node `Add` added once to the graph definition
```
node {
  name: "Add"
  op: "Add"
  input: "x/read"
  input: "y/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
```

In [62]:
# Lazy loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./lazy_loading', sess.graph)
    for _ in range(10):
        sess.run(tf.add(x, y)) # Saving 1 line of code
    writer.close()

In [64]:
# Check graph definition
# tf.get_default_graph().as_graph_def()

**Lazy** loading - Node `Add` added 10 times to the graph for above example (i.e. as many times as z is computed). Imagine computing an operation e.g. ReLU a thousand times - This makes graph bloated and slow to load, thus expensive to pass around.
```
node {
  name: "Add_1"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_2"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_3"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_4"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_5"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_6"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_7"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_8"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_9"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_10"
  op: "Add"
  input: "x_1/read"
  input: "y_1/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
```