In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

#### 1 (A)
Create two random 0-d tensors x and y of any distribution. Create a TensorFlow object that returns x + y if x > y, and x - y otherwise. Hint: look up `tf.cond()`

In [3]:
x = tf.random_normal(shape=[])
y = tf.random_uniform(shape=[])
out = tf.cond(tf.greater(x, y), true_fn=lambda: x + y, false_fn=lambda: x - y)

with tf.Session() as sess:
    x_, y_, o_ = sess.run([x, y, out])
    print('x: {}, y: {} and out: {}'.format(x_, y_, o_))

x: 1.1789909601211548, y: 0.6377964019775391 and out: 1.8167873620986938


#### 1(B)

Create two 0-d tensors x and y randomly selected from the range [-1, 1). Return x + y if x < y, x - y if x > y, 0 otherwise. Hint: Look up `tf.case()`

In [4]:
x = tf.random_uniform(shape=[], minval=-1)
y = tf.random_uniform(shape=[], minval=-1)
out = tf.case({tf.less(x, y): lambda: x + y, tf.greater(x, y): lambda: x - y}, 
              exclusive=True)

with tf.Session() as sess:
    x_, y_, o_ = sess.run([x, y, out])
    print('x: {}, y: {} and out: {}'.format(x_, y_, o_))

x: 0.6335320472717285, y: -0.7446987628936768 and out: 1.3782308101654053


#### 1(C)

Create the tensor x of the value `[[0, -2, -1], [0, 1, 2]]` and y as a tensor of zeros with the same shape as x. Return a boolean tensor that yields `True` if x equals y element-wise. Hint: Look up `tf.equal()`.

In [5]:
x = tf.constant(value=[[0, -2, -1], [0, 1, 1]])
y = tf.zeros(shape=x.shape, dtype=tf.int32)
out = tf.equal(x, y)

with tf.Session() as sess:
    print(sess.run(out))

[[ True False False]
 [ True False False]]


#### 1(D)

Create the tensor x of value 

`[29.05088806,  27.61298943,  31.19073486,  29.35532951, 30.97266006,  26.67541885,  38.08450317,  20.74983215, 34.94445419,  34.45999146,  29.06485367,  36.01657104, 27.88236427,  20.56035233,  30.20379066,  29.51215172, 33.71149445,  28.59134293,  36.05556488,  28.66994858].` 

Get the indices of elements in x whose values are greater than 30. Hint: Use `tf.where()`. Then extract elements whose values are greater than 30. Hint: Use `tf.gather()`.

In [6]:
x = tf.constant(value=[29.05088806, 27.61298943, 31.19073486, 29.35532951, 
                       30.97266006, 26.67541885, 38.08450317, 20.74983215, 
                       34.94445419, 34.45999146, 29.06485367, 36.01657104, 
                       27.88236427, 20.56035233, 30.20379066, 29.51215172, 
                       33.71149445, 28.59134293, 36.05556488, 28.66994858])

indices = tf.where(tf.greater(x, 30.0))
out = tf.gather(x, indices=indices)

with tf.Session() as sess:
    print(sess.run(out))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


#### 1(E)

Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1, 2, ..., 6. Hint: Use `tf.range()` and `tf.diag()`.

In [7]:
d = tf.range(start=1, limit=7)
m = tf.diag(diagonal=d)

with tf.Session() as sess:
    print(sess.run(m))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


#### 1(F) 

Create a random 2-d tensor of size 10 x 10 from any distribution. Calculate its determinant. Hint: Look at `tf.matrix_determinant()`.

In [8]:
m = tf.random_uniform(shape=[10, 10])
det = tf.matrix_determinant(m)

with tf.Session() as sess:
    print(sess.run(det))

0.008629425


#### 1(G)

Create tensor x with value `[5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]`. Return the unique elements in x Hint: use `tf.unique()`. Keep in mind that `tf.unique()` returns a tuple.

In [9]:
x = tf.constant(value=[5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
u = tf.unique(x)

with tf.Session() as sess:
    print(sess.run(u[0]))

[ 5  2  3 10  6  4  1  0  9]


#### 1(H)

Create two tensors x and y of shape 300 from any normal distribution, as long as they are from the same distribution. Use `tf.cond()` to return:
- The mean squared error of (x - y) if the average of all elements in (x - y) is negative, or
- The sum of absolute value of all elements in the tensor (x - y) otherwise.

In [10]:
x = tf.random_normal(shape=[300], mean=10, stddev=2.5)
y = tf.random_normal(shape=[300], mean=10, stddev=2.5)

average = tf.reduce_mean(x - y)

def mse():
    return tf.reduce_mean(tf.square(x - y))

def abse():
    return tf.reduce_sum(tf.abs(x - y))

out = tf.cond(average < 0, true_fn=mse, false_fn=abse)

with tf.Session() as sess:
    print(sess.run(out))

11.920033
